[build]
  publish = "public"
  command = "yarn run build"
[build.environment]
  YARN_VERSION = "1.7.0"
  [[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
[[headers]]
for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "form-action https:"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    Feature-Policy = "geolocation 'none'; midi 'none'; sync-xhr 'none'; microphone 'none'; camera 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; fullscreen 'none'; payment 'none'"
[[redirects]]
  from = "/download"
  to = "https://github.com/runelite-extended/launcher/releases/download/binaries/RuneLitePlusSetup.Windows64.exe"
  status = 200
  force = true
  headers = {Accepts = "application/json"}
[[redirects]]
  from = "/jar"
  to = "https://github.com/runelite-extended/launcher/releases/download/binaries/RuneLitePlus.jar"
  status = 200
  force = true
  headers = {Accepts = "application/json"}
[[redirects]]
  from = "/mac"
  to = "https://github.com/runelite-extended/launcher/releases/download/binaries/RuneLitePlus.MacOS.zip"
  status = 200
  force = true
  headers = {Accepts = "application/json"}